services:
  poste:
    image: analogic/poste.io:latest
    container_name: lunar-email-server
    hostname: ${POSTE_HOSTNAME:-mail.example.com}
    restart: unless-stopped
    network_mode: host

    environment:
      TZ: ${TZ:-America/Sao_Paulo}
      HTTPS: "OFF"
      HTTP_PORT: ${POSTE_HTTP_PORT:-3230}
      HTTPS_PORT: ${POSTE_HTTPS_PORT:-3231}

    volumes:
      - ${POSTE_DATA_PATH:-/opt/poste/data}:/data
